"use strict";

const DEFAULT_STEREO_LANGUAGE_ORDER = "eng, en";
const DEFAULT_NORMALIZE_ONLY_LANGUAGES = "eng, en";
const LEGACY_STEREO_TRACK_ORDER_VALUES = new Set(["end", "aftersource", "source", "near", "besidesource", "first", "stereofirst", "before"]);
const LANGUAGE_ALIASES = {
  en: "eng", eng: "eng",
  de: "deu", deu: "deu", ger: "deu",
  fr: "fra", fra: "fra", fre: "fra",
  es: "spa", spa: "spa",
  it: "ita", ita: "ita",
  pt: "por", por: "por", pob: "por",
  ja: "jpn", jpn: "jpn",
  ko: "kor", kor: "kor",
  zh: "zho", zho: "zho", chi: "zho", cmn: "zho", yue: "zho",
  ru: "rus", rus: "rus",
  uk: "ukr", ukr: "ukr",
  pl: "pol", pol: "pol",
  nl: "nld", nld: "nld", dut: "nld",
  sv: "swe", swe: "swe",
  da: "dan", dan: "dan",
  no: "nor", nb: "nor", nn: "nor", nor: "nor",
  fi: "fin", fin: "fin",
  tr: "tur", tur: "tur",
  ar: "ara", ara: "ara",
  he: "heb", iw: "heb", heb: "heb",
  hi: "hin", hin: "hin",
  th: "tha", tha: "tha",
  vi: "vie", vie: "vie",
  id: "ind", ind: "ind",
  ms: "msa", msa: "msa", may: "msa",
  el: "ell", ell: "ell", gre: "ell",
  ro: "ron", ron: "ron", rum: "ron",
  hu: "hun", hun: "hun",
  cs: "ces", ces: "ces", cze: "ces",
  sk: "slk", slk: "slk", slo: "slk",
  bg: "bul", bul: "bul",
  hr: "hrv", hrv: "hrv",
  sr: "srp", srp: "srp",
  sl: "slv", slv: "slv",
  lt: "lit", lit: "lit",
  lv: "lav", lav: "lav",
  et: "est", est: "est",
  ca: "cat", cat: "cat",
  eu: "eus", eus: "eus", baq: "eus",
  gl: "glg", glg: "glg",
};
const TRACK_ORDER_COPY_PRESETS = [
  "English first: eng, en",
  "German first, then English: deu, ger, de, eng, en",
  "English first, then German: eng, en, deu, ger, de",
  "Japanese/anime first: jpn, ja, eng, en, deu, ger, de",
  "Korean first: kor, ko, eng, en, deu, ger, de",
  "Chinese first: zho, chi, zh, eng, en, deu, ger, de",
  "European common: eng, en, deu, ger, de, fra, fre, fr, spa, es, ita, it, por, pt, nld, dut, nl",
  "Nordic common: eng, en, swe, sv, dan, da, nor, no, fin, fi",
  "Slavic common: eng, en, rus, ru, ukr, uk, pol, pl, ces, cze, cs, slk, slo, sk",
].join(" | ");
const COMMON_LANGUAGE_CODES = [
  "English: eng, en",
  "German: deu, ger, de",
  "French: fra, fre, fr",
  "Spanish: spa, es",
  "Italian: ita, it",
  "Portuguese: por, pt",
  "Japanese: jpn, ja",
  "Korean: kor, ko",
  "Chinese: zho, chi, zh",
  "Russian: rus, ru",
  "Ukrainian: ukr, uk",
  "Polish: pol, pl",
  "Dutch: nld, dut, nl",
  "Swedish: swe, sv",
  "Danish: dan, da",
  "Norwegian: nor, no",
  "Finnish: fin, fi",
  "Turkish: tur, tr",
  "Arabic: ara, ar",
  "Hebrew: heb, he",
  "Hindi: hin, hi",
  "Thai: tha, th",
  "Vietnamese: vie, vi",
  "Indonesian: ind, id",
  "Malay: msa, may, ms",
  "Greek: ell, gre, el",
  "Romanian: ron, rum, ro",
  "Hungarian: hun, hu",
  "Czech: ces, cze, cs",
  "Slovak: slk, slo, sk",
  "Bulgarian: bul, bg",
  "Croatian: hrv, hr",
  "Serbian: srp, sr",
  "Slovenian: slv, sl",
  "Lithuanian: lit, lt",
  "Latvian: lav, lv",
  "Estonian: est, et",
  "Catalan: cat, ca",
  "Basque: eus, baq, eu",
  "Galician: glg, gl",
].join("; ");
const STEREO_LANGUAGE_ORDER_TOOLTIP = `Default: ${DEFAULT_STEREO_LANGUAGE_ORDER}. Controls output order and generated 2-channel fallback priority. This does not choose which languages are normalized; use Normalize ONLY Languages for that. Language order uses source metadata and cannot fix missing or wrong tags. Copy presets: ${TRACK_ORDER_COPY_PRESETS}. Common codes: ${COMMON_LANGUAGE_CODES}.`;
const NORMALIZE_ONLY_LANGUAGES_TOOLTIP = `Default: ${DEFAULT_NORMALIZE_ONLY_LANGUAGES}. Comma-separated language codes to normalize, for example eng,en or deu,ger,de. Use all, *, or blank to normalize every audio stream. With Remove Other Languages on, audio outside this list is deleted. With it off, other audio is copied unchanged. If no listed language exists, Fallback To Undetected Audio can keep missing/unknown language tracks; otherwise the job fails instead of producing no audio. Common codes: ${COMMON_LANGUAGE_CODES}.`;
const REMOVE_OTHER_LANGUAGES_TOOLTIP = "Default: on. Applies when Normalize ONLY Languages is a real language list. On deletes audio streams outside that list. Off keeps the old behavior and copies other languages unchanged. No effect when Normalize ONLY Languages is all, *, or blank.";
const FALLBACK_TO_UNDETECTED_AUDIO_TOOLTIP = "Default: on. When no selected language is found, keep audio streams with missing or unknown language tags instead of failing or producing no audio. Tagged non-selected languages are still removed when Remove Other Languages is on.";

module.exports = {
  DEFAULT_NORMALIZE_ONLY_LANGUAGES,
  DEFAULT_STEREO_LANGUAGE_ORDER,
  FALLBACK_TO_UNDETECTED_AUDIO_TOOLTIP,
  LANGUAGE_ALIASES,
  LEGACY_STEREO_TRACK_ORDER_VALUES,
  NORMALIZE_ONLY_LANGUAGES_TOOLTIP,
  REMOVE_OTHER_LANGUAGES_TOOLTIP,
  STEREO_LANGUAGE_ORDER_TOOLTIP,
};
