"use strict";

const {
  createStreamProcessor,
} = require("./streamProcessor");
const {
  createStreamPipelineDeps,
} = require("./streamPipelineDeps");

function createPluginStreamContext({
  args,
  debugLogging,
  useGpuSourcePort,
  useStreamingSourcePort,
  gpuFirstPassMeasure,
  targetI,
  maxGain,
  durationSeconds,
  processingPlans,
  processingOrder,
  audioWork,
  earlyCpuPrefetch,
  earlyCpuPrefetchLimit,
  pairStereoFallbackApply,
  updateProgress,
  planLabelFor,
  describePlan,
  getCpuLoudnormRecord,
  prefetchCpuLoudnormFrom,
  prefetchNextCpuLoudnorm,
  canSplitStatsPlan,
  canFuseAnyCpuLoudnormWithSplitStats,
  startCpuLoudnormTask,
  startSplitStatsTask,
  prefetchNextSplitStats,
  splitPrefetchNextStatsDuringStats,
  splitPrefetchNextStatsAtProgress,
  processingSampleRateFor,
  buildStreamingDecodeCommand,
  buildStreamingEncodeCommand,
  buildRawApplyCommand,
  buildRawDecodeCommand,
  buildRawEncodeCommand,
  buildSourceCoreGainsCommand,
  buildStreamingGpuPlan,
  buildRawSourcePortGpuPlan,
  wrapRuntimeProfile,
  runShell,
  runChecked,
  cleanupFilesForPlan,
  pairedApplyCompleted,
  pairedFallbackApplyPartner,
  runPairedFallbackApply,
  copyOriginalPackage,
}) {
  return createStreamProcessor(createStreamPipelineDeps({
    args,
    debugLogging,
    useGpuSourcePort,
    useStreamingSourcePort,
    gpuFirstPassMeasure,
    targetI,
    maxGain,
    durationSeconds,
    processingPlans,
    processingOrder,
    audioWork,
    earlyCpuPrefetch,
    earlyCpuPrefetchLimit,
    pairStereoFallbackApply,
    updateProgress,
    planLabelFor,
    describePlan,
    getCpuLoudnormRecord,
    prefetchCpuLoudnormFrom,
    prefetchNextCpuLoudnorm,
    canSplitStatsPlan,
    canFuseAnyCpuLoudnormWithSplitStats,
    startCpuLoudnormTask,
    startSplitStatsTask,
    prefetchNextSplitStats,
    splitPrefetchNextStatsDuringStats,
    splitPrefetchNextStatsAtProgress,
    processingSampleRateFor,
    buildStreamingDecodeCommand,
    buildStreamingEncodeCommand,
    buildRawApplyCommand,
    buildRawDecodeCommand,
    buildRawEncodeCommand,
    buildSourceCoreGainsCommand,
    buildStreamingGpuPlan,
    buildRawSourcePortGpuPlan,
    wrapRuntimeProfile,
    runShell,
    runChecked,
    cleanupFilesForPlan,
    pairedApplyCompleted,
    pairedFallbackApplyPartner,
    runPairedFallbackApply,
    copyOriginalPackage,
  }));
}

module.exports = {
  createPluginStreamContext,
};
