"use strict";

function createStreamPipelineDeps({
  args,
  debugLogging,
  useGpuSourcePort,
  useStreamingSourcePort,
  gpuFirstPassMeasure,
  targetI,
  maxGain,
  durationSeconds,
  processingPlans,
  processingOrder,
  audioWork,
  earlyCpuPrefetch,
  earlyCpuPrefetchLimit,
  pairStereoFallbackApply,
  updateProgress,
  planLabelFor,
  describePlan,
  getCpuLoudnormRecord,
  prefetchCpuLoudnormFrom,
  prefetchNextCpuLoudnorm,
  canSplitStatsPlan,
  canFuseAnyCpuLoudnormWithSplitStats,
  startCpuLoudnormTask,
  startSplitStatsTask,
  prefetchNextSplitStats,
  splitPrefetchNextStatsDuringStats,
  splitPrefetchNextStatsAtProgress,
  processingSampleRateFor,
  buildStreamingDecodeCommand,
  buildStreamingEncodeCommand,
  buildRawApplyCommand,
  buildRawDecodeCommand,
  buildRawEncodeCommand,
  buildSourceCoreGainsCommand,
  buildStreamingGpuPlan,
  buildRawSourcePortGpuPlan,
  wrapRuntimeProfile,
  runShell,
  runChecked,
  cleanupFilesForPlan,
  pairedApplyCompleted,
  pairedFallbackApplyPartner,
  runPairedFallbackApply,
  copyOriginalPackage,
}) {
  return {
    commands: {
      buildRawApplyCommand,
      buildRawDecodeCommand,
      buildRawEncodeCommand,
      buildRawSourcePortGpuPlan,
      buildSourceCoreGainsCommand,
      buildStreamingDecodeCommand,
      buildStreamingEncodeCommand,
      buildStreamingGpuPlan,
      cleanupFilesForPlan,
      processingSampleRateFor,
      runChecked,
      runShell,
      wrapRuntimeProfile,
    },
    execution: {
      args,
      debugLogging,
      durationSeconds,
      gpuFirstPassMeasure,
      maxGain,
      targetI,
      useGpuSourcePort,
      useStreamingSourcePort,
    },
    output: {
      copyOriginalPackage,
    },
    pairedApply: {
      pairStereoFallbackApply,
      pairedApplyCompleted,
      pairedFallbackApplyPartner,
      runPairedFallbackApply,
    },
    plans: {
      audioWork,
      describePlan,
      planLabelFor,
      processingOrder,
      processingPlans,
    },
    prefetch: {
      earlyCpuPrefetch,
      earlyCpuPrefetchLimit,
      prefetchCpuLoudnormFrom,
    },
    progress: {
      updateProgress,
    },
    stats: {
      canFuseAnyCpuLoudnormWithSplitStats,
      canSplitStatsPlan,
      getCpuLoudnormRecord,
      prefetchNextCpuLoudnorm,
      prefetchNextSplitStats,
      splitPrefetchNextStatsAtProgress,
      splitPrefetchNextStatsDuringStats,
      startCpuLoudnormTask,
      startSplitStatsTask,
    },
  };
}

function createStreamExecutionContext(deps, policy) {
  return {
    commands: deps.commands,
    execution: deps.execution,
    output: deps.output,
    pairedApply: deps.pairedApply,
    plans: deps.plans,
    policy,
    prefetch: deps.prefetch,
    progress: deps.progress,
    stats: deps.stats,
  };
}

function createParallelStreamContext(context) {
  return {
    args: context.execution.args,
    debugLogging: context.execution.debugLogging,
    processingPlans: context.plans.processingPlans,
    streamParallelism: context.policy.streamParallelism,
    audioWork: context.plans.audioWork,
    updateProgress: context.progress.updateProgress,
    planLabelFor: context.plans.planLabelFor,
    describePlan: context.plans.describePlan,
    getCpuLoudnormRecord: context.stats.getCpuLoudnormRecord,
    targetI: context.execution.targetI,
    maxGain: context.execution.maxGain,
    buildStreamingDecodeCommand: context.commands.buildStreamingDecodeCommand,
    buildStreamingEncodeCommand: context.commands.buildStreamingEncodeCommand,
    buildStreamingGpuPlan: context.commands.buildStreamingGpuPlan,
    wrapRuntimeProfile: context.commands.wrapRuntimeProfile,
    runShell: context.commands.runShell,
    runChecked: context.commands.runChecked,
    cleanupFilesForPlan: context.commands.cleanupFilesForPlan,
    copyOriginalPackage: context.output.copyOriginalPackage,
  };
}

function createSerialPlanRunContext(context, { plan, completedWork }) {
  return {
    args: context.execution.args,
    debugLogging: context.execution.debugLogging,
    useGpuSourcePort: context.execution.useGpuSourcePort,
    useStreamingSourcePort: context.execution.useStreamingSourcePort,
    gpuFirstPassMeasure: context.execution.gpuFirstPassMeasure,
    targetI: context.execution.targetI,
    maxGain: context.execution.maxGain,
    durationSeconds: context.execution.durationSeconds,
    plan,
    completedWork,
    processingOrder: context.plans.processingOrder,
    audioWork: context.plans.audioWork,
    updateProgress: context.progress.updateProgress,
    planLabelFor: context.plans.planLabelFor,
    describePlan: context.plans.describePlan,
    getCpuLoudnormRecord: context.stats.getCpuLoudnormRecord,
    prefetchNextCpuLoudnorm: context.stats.prefetchNextCpuLoudnorm,
    canSplitStatsPlan: context.stats.canSplitStatsPlan,
    canFuseAnyCpuLoudnormWithSplitStats: context.stats.canFuseAnyCpuLoudnormWithSplitStats,
    startCpuLoudnormTask: context.stats.startCpuLoudnormTask,
    startSplitStatsTask: context.stats.startSplitStatsTask,
    prefetchNextSplitStats: context.stats.prefetchNextSplitStats,
    splitPrefetchNextStatsDuringStats: context.stats.splitPrefetchNextStatsDuringStats,
    splitPrefetchNextStatsAtProgress: context.stats.splitPrefetchNextStatsAtProgress,
    processingSampleRateFor: context.commands.processingSampleRateFor,
    buildStreamingDecodeCommand: context.commands.buildStreamingDecodeCommand,
    buildStreamingEncodeCommand: context.commands.buildStreamingEncodeCommand,
    buildRawApplyCommand: context.commands.buildRawApplyCommand,
    buildRawDecodeCommand: context.commands.buildRawDecodeCommand,
    buildRawEncodeCommand: context.commands.buildRawEncodeCommand,
    buildSourceCoreGainsCommand: context.commands.buildSourceCoreGainsCommand,
    buildStreamingGpuPlan: context.commands.buildStreamingGpuPlan,
    buildRawSourcePortGpuPlan: context.commands.buildRawSourcePortGpuPlan,
    wrapRuntimeProfile: context.commands.wrapRuntimeProfile,
    runShell: context.commands.runShell,
    runChecked: context.commands.runChecked,
    cleanupFilesForPlan: context.commands.cleanupFilesForPlan,
    pairedApplyCompleted: context.pairedApply.pairedApplyCompleted,
    pairedFallbackApplyPartner: context.pairedApply.pairedFallbackApplyPartner,
    runPairedFallbackApply: context.pairedApply.runPairedFallbackApply,
    copyOriginalPackage: context.output.copyOriginalPackage,
  };
}

module.exports = {
  createParallelStreamContext,
  createSerialPlanRunContext,
  createStreamExecutionContext,
  createStreamPipelineDeps,
};
