"use strict";

const {
  createPairedApplyCoordinator,
} = require("./pairedApplyCoordinator");

function createPluginPairedApplyContext({
  args,
  debugLogging,
  useGpuSourcePort,
  useStreamingSourcePort,
  audioPlans,
  skippedAudioPlans,
  audioStreams,
  container,
  tmpOutputFilePath,
  pythonPath,
  targetI,
  maxGain,
  durationSeconds,
  audioBitrate,
  rawInputAudioArgs,
  encodeSampleRateArgsFor,
  encodeThreadArgs,
  canSkipOriginalAformat,
  processingSampleRateFor,
  needsInlineStereoDownmix,
  usesStereoFallbackSourcePath,
  canSplitStatsPlan,
  canFuseAnyCpuLoudnormWithSplitStats,
  startCpuLoudnormTask,
  startSplitStatsTask,
  getCpuLoudnormRecord,
  buildStreamingDecodeCommand,
  buildStreamingEncodeCommand,
  buildStreamingGpuPlan,
  buildPairedStreamingGpuPlan,
  wrapRuntimeProfile,
  runShell,
  runChecked,
  cleanupFilesForPlan,
  planLabelFor,
  updateProgress,
}) {
  return createPairedApplyCoordinator({
    args,
    debugLogging,
    useGpuSourcePort,
    useStreamingSourcePort,
    audioPlans,
    skippedAudioPlans,
    audioStreams,
    container,
    tmpOutputFilePath,
    pythonPath,
    targetI,
    maxGain,
    durationSeconds,
    audioBitrate,
    rawInputAudioArgs,
    encodeSampleRateArgsFor,
    encodeThreadArgs,
    canSkipOriginalAformat,
    processingSampleRateFor,
    needsInlineStereoDownmix,
    usesStereoFallbackSourcePath,
    canSplitStatsPlan,
    canFuseAnyCpuLoudnormWithSplitStats,
    startCpuLoudnormTask,
    startSplitStatsTask,
    getCpuLoudnormRecord,
    buildStreamingDecodeCommand,
    buildStreamingEncodeCommand,
    buildStreamingGpuPlan,
    buildPairedStreamingGpuPlan,
    wrapRuntimeProfile,
    runShell,
    runChecked,
    cleanupFilesForPlan,
    planLabelFor,
    updateProgress,
  });
}

module.exports = {
  createPluginPairedApplyContext,
};
