"use strict";

const {
  runSerialRawApply,
  runSerialStreamingApply,
} = require("./streamSerialApplyBranches");

async function runSerialApplyDispatch({
  args,
  debugLogging,
  useGpuSourcePort,
  useStreamingSourcePort,
  targetI,
  maxGain,
  durationSeconds,
  plan,
  planLabel,
  describePlan,
  completedWork,
  measureSpan,
  decodeSpan,
  normalizeSpan,
  encodeSpan,
  streamStartedAt,
  splitStatsForPlan,
  firstPassStatsCacheInput,
  splitStatsCacheInput,
  cpuLoudnormValues,
  buildStreamingDecodeCommand,
  buildStreamingEncodeCommand,
  buildRawApplyCommand,
  buildRawDecodeCommand,
  buildRawEncodeCommand,
  buildSourceCoreGainsCommand,
  buildStreamingGpuPlan,
  buildRawSourcePortGpuPlan,
  wrapRuntimeProfile,
  runShell,
  runChecked,
  cleanupFilesForPlan,
  copyOriginalPackage,
  updateProgress,
}) {
  if (useStreamingSourcePort) {
    return await runSerialStreamingApply({
      args,
      debugLogging,
      plan,
      planLabel,
      describePlan,
      completedWork,
      measureSpan,
      decodeSpan,
      normalizeSpan,
      encodeSpan,
      streamStartedAt,
      splitStatsForPlan,
      firstPassStatsCacheInput,
      splitStatsCacheInput,
      cpuLoudnormValues,
      buildStreamingDecodeCommand,
      buildStreamingEncodeCommand,
      buildStreamingGpuPlan,
      wrapRuntimeProfile,
      runShell,
      runChecked,
      cleanupFilesForPlan,
      copyOriginalPackage,
      updateProgress,
    });
  }

  return await runSerialRawApply({
    args,
    debugLogging,
    plan,
    planLabel,
    describePlan,
    completedWork,
    measureSpan,
    decodeSpan,
    normalizeSpan,
    encodeSpan,
    streamStartedAt,
    durationSeconds,
    cpuLoudnormValues,
    useGpuSourcePort,
    targetI,
    maxGain,
    buildRawApplyCommand,
    buildRawDecodeCommand,
    buildRawEncodeCommand,
    buildRawSourcePortGpuPlan,
    buildSourceCoreGainsCommand,
    wrapRuntimeProfile,
    runShell,
    runChecked,
    copyOriginalPackage,
    updateProgress,
  });
}

module.exports = {
  runSerialApplyDispatch,
};
