"use strict";

const {
  runStreamParallelProcessing,
} = require("./streamParallelProcessor");
const {
  runSerialStreamProcessing,
} = require("./streamSerialProcessor");

async function runStreamProcessorRoute({
  args,
  debugLogging,
  useGpuSourcePort,
  useStreamingSourcePort,
  targetI,
  maxGain,
  durationSeconds,
  processingPlans,
  processingOrder,
  audioWork,
  streamParallelism,
  useStreamParallelism,
  updateProgress,
  planLabelFor,
  describePlan,
  getCpuLoudnormRecord,
  prefetchNextCpuLoudnorm,
  canSplitStatsPlan,
  canFuseAnyCpuLoudnormWithSplitStats,
  startCpuLoudnormTask,
  startSplitStatsTask,
  prefetchNextSplitStats,
  splitPrefetchNextStatsDuringStats,
  splitPrefetchNextStatsAtProgress,
  processingSampleRateFor,
  buildStreamingDecodeCommand,
  buildStreamingEncodeCommand,
  buildRawApplyCommand,
  buildRawDecodeCommand,
  buildRawEncodeCommand,
  buildSourceCoreGainsCommand,
  buildStreamingGpuPlan,
  buildRawSourcePortGpuPlan,
  wrapRuntimeProfile,
  runShell,
  runChecked,
  cleanupFilesForPlan,
  pairedApplyCompleted,
  pairedFallbackApplyPartner,
  runPairedFallbackApply,
  copyOriginalPackage,
}) {
  if (useStreamParallelism) {
    return await runStreamParallelProcessing({
      args,
      debugLogging,
      processingPlans,
      streamParallelism,
      audioWork,
      updateProgress,
      planLabelFor,
      describePlan,
      getCpuLoudnormRecord,
      targetI,
      maxGain,
      buildStreamingDecodeCommand,
      buildStreamingEncodeCommand,
      buildStreamingGpuPlan,
      wrapRuntimeProfile,
      runShell,
      runChecked,
      cleanupFilesForPlan,
      copyOriginalPackage,
    });
  }
  return await runSerialStreamProcessing({
    args,
    debugLogging,
    useGpuSourcePort,
    useStreamingSourcePort,
    targetI,
    maxGain,
    durationSeconds,
    processingPlans,
    processingOrder,
    updateProgress,
    planLabelFor,
    describePlan,
    getCpuLoudnormRecord,
    prefetchNextCpuLoudnorm,
    canSplitStatsPlan,
    canFuseAnyCpuLoudnormWithSplitStats,
    startCpuLoudnormTask,
    startSplitStatsTask,
    prefetchNextSplitStats,
    splitPrefetchNextStatsDuringStats,
    splitPrefetchNextStatsAtProgress,
    processingSampleRateFor,
    buildStreamingDecodeCommand,
    buildStreamingEncodeCommand,
    buildRawApplyCommand,
    buildRawDecodeCommand,
    buildRawEncodeCommand,
    buildSourceCoreGainsCommand,
    buildStreamingGpuPlan,
    buildRawSourcePortGpuPlan,
    wrapRuntimeProfile,
    runShell,
    runChecked,
    cleanupFilesForPlan,
    pairedApplyCompleted,
    pairedFallbackApplyPartner,
    runPairedFallbackApply,
    copyOriginalPackage,
  });
}

module.exports = {
  runStreamProcessorRoute,
};
